--- findlib-1.2.4/Makefile	2009-02-16 02:12:09.000000000 +0100
+++ findlib-1.2.4-patched/Makefile	2010-06-08 09:09:29.901369711 +0200
@@ -19,6 +19,7 @@
 install:
 	mkdir -p "$(prefix)$(OCAMLFIND_BIN)"
 	mkdir -p "$(prefix)$(OCAMLFIND_MAN)"
+	mkdir -p "$(prefix)$(OCAML_CORE_STDLIB)"
 	for p in $(PARTS); do ( cd src/$$p; $(MAKE) install ); done
 	$(MAKE) install-meta
 	cd src/findlib; $(MAKE) install-num-top
